-- All timestamps are UTC epoch milliseconds. Display and service-day rules are applied in the Worker.
-- IDs are generated by the application as UUIDs; legacy Google Sheets IDs are retained only during import.

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  legacy_user_id TEXT UNIQUE,
  nickname TEXT NOT NULL COLLATE NOCASE UNIQUE,
  password_hash TEXT NOT NULL,
  blog_url TEXT NOT NULL COLLATE NOCASE UNIQUE,
  blog_name TEXT NOT NULL,
  account_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (account_status IN ('pending', 'approved', 'rejected', 'locked')),
  approved_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE user_roles (
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('admin')),
  granted_at INTEGER NOT NULL,
  PRIMARY KEY (user_id, role)
);

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at INTEGER NOT NULL,
  revoked_at INTEGER,
  created_at INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL
);

CREATE INDEX sessions_active_by_user ON sessions(user_id, expires_at);

CREATE TABLE rooms (
  id TEXT PRIMARY KEY,
  legacy_room_id TEXT UNIQUE,
  name TEXT NOT NULL,
  room_type TEXT NOT NULL CHECK (room_type IN ('keyword', 'link')),
  creator_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  join_starts_at INTEGER NOT NULL,
  join_ends_at INTEGER NOT NULL,
  closes_at INTEGER NOT NULL,
  missions_json TEXT NOT NULL,
  room_status TEXT NOT NULL DEFAULT 'waiting'
    CHECK (room_status IN ('waiting', 'in_progress', 'closed', 'deleted')),
  closed_at INTEGER,
  deleted_at INTEGER,
  created_at INTEGER NOT NULL,
  CHECK (join_starts_at < join_ends_at),
  CHECK (join_ends_at < closes_at)
);

CREATE INDEX rooms_by_status_and_start ON rooms(room_status, join_starts_at);
CREATE INDEX rooms_by_creator ON rooms(creator_id, created_at DESC);

CREATE TABLE room_participants (
  id TEXT PRIMARY KEY,
  legacy_participant_id TEXT UNIQUE,
  room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  keyword TEXT,
  link_url TEXT,
  joined_at INTEGER NOT NULL,
  completed_at INTEGER,
  CHECK ((keyword IS NOT NULL AND link_url IS NULL) OR (keyword IS NULL AND link_url IS NOT NULL)),
  UNIQUE (room_id, user_id)
);

CREATE INDEX room_participants_by_user ON room_participants(user_id, joined_at DESC);

CREATE TABLE visits (
  id TEXT PRIMARY KEY,
  legacy_visit_id TEXT UNIQUE,
  room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  visitor_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  visited_at INTEGER NOT NULL,
  CHECK (visitor_id <> target_id),
  UNIQUE (room_id, visitor_id, target_id)
);

CREATE INDEX visits_by_room_and_visitor ON visits(room_id, visitor_id);

CREATE TABLE penalties (
  id TEXT PRIMARY KEY,
  legacy_penalty_id TEXT UNIQUE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL CHECK (reason IN ('auto_incomplete', 'participant_report', 'admin')),
  status TEXT NOT NULL DEFAULT 'unresolved' CHECK (status IN ('unresolved', 'resolved')),
  issued_at INTEGER NOT NULL,
  resolved_at INTEGER,
  locked_at INTEGER,
  UNIQUE (room_id, user_id)
);

CREATE INDEX penalties_unresolved_by_user ON penalties(user_id, status, issued_at);

CREATE TABLE reports (
  id TEXT PRIMARY KEY,
  legacy_report_id TEXT UNIQUE,
  reporter_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  target_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  room_id TEXT REFERENCES rooms(id) ON DELETE RESTRICT,
  reason TEXT NOT NULL,
  report_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (report_status IN ('pending', 'resolved', 'dismissed')),
  created_at INTEGER NOT NULL,
  resolved_at INTEGER,
  resolved_by TEXT REFERENCES users(id) ON DELETE RESTRICT,
  CHECK (reporter_id <> target_id)
);

CREATE INDEX reports_by_status ON reports(report_status, created_at DESC);

CREATE TABLE audit_logs (
  id TEXT PRIMARY KEY,
  legacy_log_id TEXT UNIQUE,
  actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL
);

CREATE INDEX audit_logs_by_created_at ON audit_logs(created_at DESC);
